AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 125
  Exclude:
    - "spec/**/*.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/CyclomaticComplexity:
  Exclude:
    - "spec/**/*.rb"

Metrics/PerceivedComplexity:
  Exclude:
   - "spec/**/*.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/amplitude-experiment.rb # Gem name, added for easier Gemfile usage

Metrics/ClassLength:
  Max: 120
