AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "amplitude-experiment.gemspec"

Layout/LineLength:
  Enabled: false
  Exclude:
    - "spec/**/*.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/amplitude-experiment.rb # Gem name, added for easier Gemfile usage

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
