AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 125
  Exclude:
    - "spec/**/*.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
