name: Publish Docs

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          
      - name: Setup Docs
        run:  bundle exec rake yard

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@0f24da7de3e7e135102609a4c9633b025be8411b # 4.1.5
        with:
          branch: gh-pages
          folder: doc
